# Generated by Django 5.2.17 on 2026-09-05 10:20

import django.db.models.deletion
import wartung.models.benutzer
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bereich",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bezeichnung",
                    models.CharField(
                        blank=True,
                        help_text='Zusatz zur Unterscheidung, z. B. "Nord" oder "OG".',
                        max_length=80,
                        verbose_name="Bezeichnung",
                    ),
                ),
                ("notiz", models.TextField(blank=True, verbose_name="Notiz")),
            ],
            options={
                "verbose_name": "Bereich",
                "verbose_name_plural": "Bereiche",
                "ordering": ["objekt__name", "typ__sortierung", "bezeichnung"],
            },
        ),
        migrations.CreateModel(
            name="BereichsTyp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name_de",
                    models.CharField(
                        max_length=120, verbose_name="Bezeichnung (Deutsch)"
                    ),
                ),
                (
                    "name_en",
                    models.CharField(
                        blank=True,
                        max_length=120,
                        verbose_name="Bezeichnung (Englisch)",
                    ),
                ),
                (
                    "name_sv",
                    models.CharField(
                        blank=True,
                        max_length=120,
                        verbose_name="Bezeichnung (Schwedisch)",
                    ),
                ),
                (
                    "schluessel",
                    models.SlugField(unique=True, verbose_name="Schluessel"),
                ),
                (
                    "sortierung",
                    models.PositiveSmallIntegerField(
                        default=100, verbose_name="Sortierung"
                    ),
                ),
            ],
            options={
                "verbose_name": "Bereichstyp",
                "verbose_name_plural": "Bereichstypen",
                "ordering": ["sortierung", "name_de"],
            },
        ),
        migrations.CreateModel(
            name="Objekt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, verbose_name="Name")),
                (
                    "aktiv_ab_monat",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Leer lassen fuer ganzjaehrig. Beispiel Sommerhaus: 4 bis 10.",
                        null=True,
                        verbose_name="Ruhezeit: aktiv ab Monat",
                    ),
                ),
                (
                    "aktiv_bis_monat",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Ruhezeit: aktiv bis Monat"
                    ),
                ),
                ("notiz", models.TextField(blank=True, verbose_name="Notiz")),
                ("angelegt_am", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Objekt",
                "verbose_name_plural": "Objekte",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ObjektTyp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name_de",
                    models.CharField(
                        max_length=120, verbose_name="Bezeichnung (Deutsch)"
                    ),
                ),
                (
                    "name_en",
                    models.CharField(
                        blank=True,
                        max_length=120,
                        verbose_name="Bezeichnung (Englisch)",
                    ),
                ),
                (
                    "name_sv",
                    models.CharField(
                        blank=True,
                        max_length=120,
                        verbose_name="Bezeichnung (Schwedisch)",
                    ),
                ),
                (
                    "schluessel",
                    models.SlugField(unique=True, verbose_name="Schluessel"),
                ),
                (
                    "sortierung",
                    models.PositiveSmallIntegerField(
                        default=100, verbose_name="Sortierung"
                    ),
                ),
            ],
            options={
                "verbose_name": "Objekttyp",
                "verbose_name_plural": "Objekttypen",
                "ordering": ["sortierung", "name_de"],
            },
        ),
        migrations.CreateModel(
            name="Benutzer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="E-Mail"
                    ),
                ),
                (
                    "name",
                    models.CharField(blank=True, max_length=120, verbose_name="Name"),
                ),
                (
                    "sprache",
                    models.CharField(
                        choices=[
                            ("de", "Deutsch"),
                            ("en", "Englisch"),
                            ("sv", "Schwedisch"),
                        ],
                        default="de",
                        help_text="Bestimmt Oberflaeche und Sprache der Wochenmail.",
                        max_length=2,
                        verbose_name="Sprache",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="aktiv")),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False, verbose_name="Zugang zur Verwaltung"
                    ),
                ),
                (
                    "angelegt_am",
                    models.DateTimeField(auto_now_add=True, verbose_name="angelegt am"),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "Benutzer",
                "verbose_name_plural": "Benutzer",
                "ordering": ["email"],
            },
            managers=[
                ("objects", wartung.models.benutzer.BenutzerManager()),
            ],
        ),
        migrations.CreateModel(
            name="Aufgabe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "intervall_wert",
                    models.PositiveIntegerField(verbose_name="Intervall"),
                ),
                (
                    "intervall_einheit",
                    models.CharField(
                        choices=[
                            ("tage", "Tage"),
                            ("monate", "Monate"),
                            ("jahre", "Jahre"),
                        ],
                        max_length=10,
                        verbose_name="Einheit",
                    ),
                ),
                (
                    "modus",
                    models.CharField(
                        choices=[
                            ("relativ", "Relativ zur letzten Erledigung"),
                            ("kalender", "Fester Kalenderrhythmus"),
                        ],
                        default="relativ",
                        max_length=10,
                        verbose_name="Modus",
                    ),
                ),
                (
                    "kalender_monat",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Nur beim festen Kalenderrhythmus.",
                        null=True,
                        verbose_name="Monat",
                    ),
                ),
                (
                    "kalender_tag",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Nur beim festen Kalenderrhythmus.",
                        null=True,
                        verbose_name="Tag",
                    ),
                ),
                ("aktiv", models.BooleanField(default=True, verbose_name="aktiv")),
                ("notiz", models.TextField(blank=True, verbose_name="Notiz")),
                (
                    "bereich",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aufgaben",
                        to="wartung.bereich",
                        verbose_name="Bereich",
                    ),
                ),
            ],
            options={
                "verbose_name": "Aufgabe",
                "verbose_name_plural": "Aufgaben",
                "ordering": [
                    "bereich__objekt__name",
                    "bereich__typ__sortierung",
                    "taetigkeit__sortierung",
                ],
            },
        ),
        migrations.AddField(
            model_name="bereich",
            name="typ",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="bereiche",
                to="wartung.bereichstyp",
                verbose_name="Typ",
            ),
        ),
        migrations.AddField(
            model_name="bereich",
            name="objekt",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bereiche",
                to="wartung.objekt",
                verbose_name="Objekt",
            ),
        ),
        migrations.AddField(
            model_name="objekt",
            name="typ",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="objekte",
                to="wartung.objekttyp",
                verbose_name="Typ",
            ),
        ),
        migrations.CreateModel(
            name="Taetigkeit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name_de",
                    models.CharField(
                        max_length=120, verbose_name="Bezeichnung (Deutsch)"
                    ),
                ),
                (
                    "name_en",
                    models.CharField(
                        blank=True,
                        max_length=120,
                        verbose_name="Bezeichnung (Englisch)",
                    ),
                ),
                (
                    "name_sv",
                    models.CharField(
                        blank=True,
                        max_length=120,
                        verbose_name="Bezeichnung (Schwedisch)",
                    ),
                ),
                (
                    "schluessel",
                    models.SlugField(unique=True, verbose_name="Schluessel"),
                ),
                (
                    "hinweis_de",
                    models.TextField(blank=True, verbose_name="Hinweis (Deutsch)"),
                ),
                (
                    "hinweis_en",
                    models.TextField(blank=True, verbose_name="Hinweis (Englisch)"),
                ),
                (
                    "hinweis_sv",
                    models.TextField(blank=True, verbose_name="Hinweis (Schwedisch)"),
                ),
                (
                    "standard_intervall_wert",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="uebliches Intervall"
                    ),
                ),
                (
                    "standard_intervall_einheit",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("tage", "Tage"),
                            ("monate", "Monate"),
                            ("jahre", "Jahre"),
                        ],
                        max_length=10,
                        verbose_name="Einheit",
                    ),
                ),
                (
                    "standard_modus",
                    models.CharField(
                        choices=[
                            ("relativ", "Relativ zur letzten Erledigung"),
                            ("kalender", "Fester Kalenderrhythmus"),
                        ],
                        default="relativ",
                        max_length=10,
                        verbose_name="Modus",
                    ),
                ),
                (
                    "standard_kalender_monat",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Monat im Kalenderrhythmus"
                    ),
                ),
                (
                    "sortierung",
                    models.PositiveSmallIntegerField(
                        default=100, verbose_name="Sortierung"
                    ),
                ),
                (
                    "bereichs_typen",
                    models.ManyToManyField(
                        blank=True,
                        related_name="taetigkeiten",
                        to="wartung.bereichstyp",
                        verbose_name="passt zu Bereichstypen",
                    ),
                ),
            ],
            options={
                "verbose_name": "Taetigkeit",
                "verbose_name_plural": "Taetigkeiten",
                "ordering": ["sortierung", "name_de"],
            },
        ),
        migrations.CreateModel(
            name="Ereignis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "beschreibung",
                    models.CharField(
                        blank=True,
                        help_text="Nur noetig, wenn keine Taetigkeit aus dem Katalog passt.",
                        max_length=200,
                        verbose_name="Beschreibung",
                    ),
                ),
                ("datum", models.DateField(db_index=True, verbose_name="Datum")),
                (
                    "kosten",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Kosten",
                    ),
                ),
                (
                    "ausgefuehrt_von",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="ausgefuehrt von"
                    ),
                ),
                (
                    "notiz",
                    models.TextField(
                        blank=True,
                        help_text='Material, Farbton, Menge -- z. B. "RAL 7016, 12 l".',
                        verbose_name="Notiz",
                    ),
                ),
                ("erfasst_am", models.DateTimeField(auto_now_add=True)),
                (
                    "aufgabe",
                    models.ForeignKey(
                        blank=True,
                        help_text="Leer lassen bei einmaligen Vorgaengen.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ereignisse",
                        to="wartung.aufgabe",
                        verbose_name="Aufgabe",
                    ),
                ),
                (
                    "bereich",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ereignisse",
                        to="wartung.bereich",
                        verbose_name="Bereich",
                    ),
                ),
                (
                    "erfasst_von",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ereignisse",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="erfasst von",
                    ),
                ),
                (
                    "taetigkeit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ereignisse",
                        to="wartung.taetigkeit",
                        verbose_name="Taetigkeit",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ereignis",
                "verbose_name_plural": "Ereignisse",
                "ordering": ["-datum", "-erfasst_am"],
            },
        ),
        migrations.AddField(
            model_name="aufgabe",
            name="taetigkeit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="aufgaben",
                to="wartung.taetigkeit",
                verbose_name="Taetigkeit",
            ),
        ),
        migrations.AddConstraint(
            model_name="bereich",
            constraint=models.UniqueConstraint(
                fields=("objekt", "typ", "bezeichnung"),
                name="bereich_je_objekt_eindeutig",
            ),
        ),
        migrations.AddConstraint(
            model_name="objekt",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("aktiv_ab_monat__isnull", True),
                    models.Q(("aktiv_ab_monat__gte", 1), ("aktiv_ab_monat__lte", 12)),
                    _connector="OR",
                ),
                name="objekt_aktiv_ab_1_bis_12",
            ),
        ),
        migrations.AddConstraint(
            model_name="objekt",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("aktiv_bis_monat__isnull", True),
                    models.Q(("aktiv_bis_monat__gte", 1), ("aktiv_bis_monat__lte", 12)),
                    _connector="OR",
                ),
                name="objekt_aktiv_bis_1_bis_12",
            ),
        ),
        migrations.AddConstraint(
            model_name="objekt",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("aktiv_ab_monat__isnull", True),
                        ("aktiv_bis_monat__isnull", True),
                    ),
                    models.Q(
                        ("aktiv_ab_monat__isnull", False),
                        ("aktiv_bis_monat__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="objekt_ruhezeit_vollstaendig",
            ),
        ),
        migrations.AddConstraint(
            model_name="taetigkeit",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("standard_kalender_monat__isnull", True),
                    models.Q(
                        ("standard_kalender_monat__gte", 1),
                        ("standard_kalender_monat__lte", 12),
                    ),
                    _connector="OR",
                ),
                name="taetigkeit_kalendermonat_1_bis_12",
            ),
        ),
        migrations.AddIndex(
            model_name="ereignis",
            index=models.Index(
                fields=["aufgabe", "-datum"], name="ereignis_aufgabe_datum"
            ),
        ),
        migrations.AddConstraint(
            model_name="ereignis",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("taetigkeit__isnull", False),
                    models.Q(("beschreibung", ""), _negated=True),
                    _connector="OR",
                ),
                name="ereignis_braucht_taetigkeit_oder_beschreibung",
            ),
        ),
        migrations.AddConstraint(
            model_name="aufgabe",
            constraint=models.UniqueConstraint(
                fields=("bereich", "taetigkeit"), name="aufgabe_je_bereich_eindeutig"
            ),
        ),
        migrations.AddConstraint(
            model_name="aufgabe",
            constraint=models.CheckConstraint(
                condition=models.Q(("intervall_wert__gte", 1)),
                name="aufgabe_intervall_positiv",
            ),
        ),
        migrations.AddConstraint(
            model_name="aufgabe",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("modus", "kalender"), _negated=True),
                    ("kalender_monat__isnull", False),
                    _connector="OR",
                ),
                name="aufgabe_kalendermodus_braucht_monat",
            ),
        ),
        migrations.AddConstraint(
            model_name="aufgabe",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("kalender_monat__isnull", True),
                    models.Q(("kalender_monat__gte", 1), ("kalender_monat__lte", 12)),
                    _connector="OR",
                ),
                name="aufgabe_kalendermonat_1_bis_12",
            ),
        ),
        migrations.AddConstraint(
            model_name="aufgabe",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("kalender_tag__isnull", True),
                    models.Q(("kalender_tag__gte", 1), ("kalender_tag__lte", 31)),
                    _connector="OR",
                ),
                name="aufgabe_kalendertag_1_bis_31",
            ),
        ),
    ]
