# Generated by Django 5.2.17 on 2026-09-05 10:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wartung", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="aufgabe",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("modus", "kalender"), _negated=True),
                    ("intervall_einheit", "jahre"),
                    _connector="OR",
                ),
                name="aufgabe_kalendermodus_braucht_jahre",
            ),
        ),
    ]
