# Generated by Django 5.2.17 on 2026-09-05 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wartung", "0002_aufgabe_aufgabe_kalendermodus_braucht_jahre"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="taetigkeit",
            options={
                "ordering": ["sortierung", "name_de"],
                "verbose_name": "Tätigkeit",
                "verbose_name_plural": "Tätigkeiten",
            },
        ),
        migrations.AlterField(
            model_name="aufgabe",
            name="taetigkeit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="aufgaben",
                to="wartung.taetigkeit",
                verbose_name="Tätigkeit",
            ),
        ),
        migrations.AlterField(
            model_name="benutzer",
            name="sprache",
            field=models.CharField(
                choices=[("de", "Deutsch"), ("en", "Englisch"), ("sv", "Schwedisch")],
                default="de",
                help_text="Bestimmt Oberfläche und Sprache der Wochenmail.",
                max_length=2,
                verbose_name="Sprache",
            ),
        ),
        migrations.AlterField(
            model_name="bereichstyp",
            name="schluessel",
            field=models.SlugField(unique=True, verbose_name="Schlüssel"),
        ),
        migrations.AlterField(
            model_name="ereignis",
            name="aufgabe",
            field=models.ForeignKey(
                blank=True,
                help_text="Leer lassen bei einmaligen Vorgängen.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ereignisse",
                to="wartung.aufgabe",
                verbose_name="Aufgabe",
            ),
        ),
        migrations.AlterField(
            model_name="ereignis",
            name="ausgefuehrt_von",
            field=models.CharField(
                blank=True, max_length=120, verbose_name="ausgeführt von"
            ),
        ),
        migrations.AlterField(
            model_name="ereignis",
            name="beschreibung",
            field=models.CharField(
                blank=True,
                help_text="Nur nötig, wenn keine Tätigkeit aus dem Katalog passt.",
                max_length=200,
                verbose_name="Beschreibung",
            ),
        ),
        migrations.AlterField(
            model_name="ereignis",
            name="notiz",
            field=models.TextField(
                blank=True,
                help_text='Material, Farbton, Menge – z. B. "RAL 7016, 12 l".',
                verbose_name="Notiz",
            ),
        ),
        migrations.AlterField(
            model_name="ereignis",
            name="taetigkeit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ereignisse",
                to="wartung.taetigkeit",
                verbose_name="Tätigkeit",
            ),
        ),
        migrations.AlterField(
            model_name="objekt",
            name="aktiv_ab_monat",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Leer lassen für ganzjährig. Beispiel Sommerhaus: 4 bis 10.",
                null=True,
                verbose_name="Ruhezeit: aktiv ab Monat",
            ),
        ),
        migrations.AlterField(
            model_name="objekttyp",
            name="schluessel",
            field=models.SlugField(unique=True, verbose_name="Schlüssel"),
        ),
        migrations.AlterField(
            model_name="taetigkeit",
            name="schluessel",
            field=models.SlugField(unique=True, verbose_name="Schlüssel"),
        ),
        migrations.AlterField(
            model_name="taetigkeit",
            name="standard_intervall_wert",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="übliches Intervall"
            ),
        ),
    ]
