# Generated by Django 5.2.17 on 2026-09-05 11:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wartung", "0003_alter_taetigkeit_options_alter_aufgabe_taetigkeit_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Zugangsmarke",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "schluessel_hash",
                    models.CharField(db_index=True, max_length=64, unique=True),
                ),
                (
                    "zweck",
                    models.CharField(
                        choices=[
                            ("anmeldung", "Anmeldung"),
                            ("erledigung", "Erledigung"),
                        ],
                        max_length=12,
                    ),
                ),
                ("erstellt_am", models.DateTimeField(auto_now_add=True)),
                ("gueltig_bis", models.DateTimeField()),
                ("verbraucht_am", models.DateTimeField(blank=True, null=True)),
                (
                    "aufgabe",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="marken",
                        to="wartung.aufgabe",
                    ),
                ),
                (
                    "benutzer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="marken",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Zugangsmarke",
                "verbose_name_plural": "Zugangsmarken",
                "ordering": ["-erstellt_am"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("zweck", "erledigung"), _negated=True),
                            ("aufgabe__isnull", False),
                            _connector="OR",
                        ),
                        name="abhakmarke_braucht_aufgabe",
                    )
                ],
            },
        ),
    ]
