# Generated by Django 5.2.17 on 2026-09-05 11:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wartung", "0005_benutzer_kalender_schluessel"),
    ]

    operations = [
        migrations.CreateModel(
            name="Mailversand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "woche",
                    models.CharField(max_length=9, unique=True, verbose_name="Woche"),
                ),
                (
                    "gesendet_am",
                    models.DateTimeField(auto_now_add=True, verbose_name="gesendet am"),
                ),
                (
                    "anzahl_mails",
                    models.PositiveIntegerField(default=0, verbose_name="Anzahl Mails"),
                ),
                (
                    "anzahl_eintraege",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Anzahl Einträge"
                    ),
                ),
            ],
            options={
                "verbose_name": "Mailversand",
                "verbose_name_plural": "Mailversand",
                "ordering": ["-gesendet_am"],
            },
        ),
    ]
