# Generated by Django 5.2.17 on 2026-09-05 16:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wartung", "0006_mailversand"),
    ]

    operations = [
        migrations.AddField(
            model_name="benutzer",
            name="zugewiesene_objekte",
            field=models.ManyToManyField(
                blank=True,
                help_text="Wer hier zugewiesen ist, sieht dieses Objekt samt Bereichen, Aufgaben und Ereignissen. Verwaltungsberechtigte sehen ohnehin alles.",
                related_name="betreuer",
                to="wartung.objekt",
                verbose_name="zugewiesene Objekte",
            ),
        ),
    ]
