# Generated by Django 5.2.17 on 2026-09-09 18:25

import django.db.models.deletion
import uuid
import wartung.models.anhang
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wartung", "0007_benutzer_zugewiesene_objekte"),
    ]

    operations = [
        migrations.CreateModel(
            name="Anhang",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kennung",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "datei",
                    models.FileField(
                        max_length=300,
                        upload_to=wartung.models.anhang.ablagepfad,
                        verbose_name="Datei",
                    ),
                ),
                (
                    "vorschau",
                    models.ImageField(
                        blank=True,
                        max_length=300,
                        null=True,
                        upload_to=wartung.models.anhang.vorschaupfad,
                        verbose_name="Vorschau",
                    ),
                ),
                (
                    "dateiname",
                    models.CharField(
                        max_length=255, verbose_name="ursprünglicher Dateiname"
                    ),
                ),
                (
                    "inhaltstyp",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Inhaltstyp"
                    ),
                ),
                (
                    "groesse",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Größe in Bytes"
                    ),
                ),
                (
                    "beschriftung",
                    models.CharField(
                        blank=True,
                        help_text='Etwa "Typenschild" oder "Rechnung Fa. Berg".',
                        max_length=200,
                        verbose_name="Beschriftung",
                    ),
                ),
                ("hochgeladen_am", models.DateTimeField(auto_now_add=True)),
                (
                    "bereich",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="anhaenge",
                        to="wartung.bereich",
                        verbose_name="Bereich",
                    ),
                ),
                (
                    "ereignis",
                    models.ForeignKey(
                        blank=True,
                        help_text="Leer lassen bei Unterlagen, die zum Bauteil gehören.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="anhaenge",
                        to="wartung.ereignis",
                        verbose_name="Ereignis",
                    ),
                ),
                (
                    "hochgeladen_von",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="anhaenge",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="hochgeladen von",
                    ),
                ),
            ],
            options={
                "verbose_name": "Anhang",
                "verbose_name_plural": "Anhänge",
                "ordering": ["hochgeladen_am"],
            },
        ),
    ]
