# Generated by Django 5.2.17 on 2026-09-11 17:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wartung", "0008_anhang"),
    ]

    operations = [
        migrations.AddField(
            model_name="ereignis",
            name="absendekennung",
            field=models.UUIDField(blank=True, editable=False, null=True, unique=True),
        ),
    ]
