"""Startbestand des dreisprachigen Vorlagenkatalogs (SPEC 7).

Der Katalog transportiert Fachwissen, nicht nur gesparte Tipparbeit: Der
Hinweistext beantwortet "woran haette ich denken muessen". Intervalle sind
uebliche Richtwerte -- die Herstellerangabe des konkreten Geraets geht vor.

Die schwedischen Fachbegriffe sind gegenzulesen (SPEC 10.6).
"""

# (schluessel, de, en, sv, sortierung)
OBJEKT_TYPEN = [
    ("haus", "Haus", "House", "Hus", 10),
    ("sommerhaus", "Sommerhaus", "Summer house", "Sommarstuga", 20),
    ("wohnung", "Wohnung", "Apartment", "Lägenhet", 30),
    ("garage", "Garage", "Garage", "Garage", 40),
    ("nebengebaeude", "Nebengebäude", "Outbuilding", "Uthus", 50),
]

BEREICHS_TYPEN = [
    ("waermepumpe", "Wärmepumpe", "Heat pump", "Värmepump", 10),
    ("klimageraet", "Klimagerät", "Air conditioner", "Luftkonditionering", 20),
    ("lueftung", "Lüftungsanlage", "Ventilation system", "Ventilationsaggregat", 30),
    ("heizung", "Heizung", "Heating system", "Värmesystem", 40),
    ("fassade", "Fassade", "Facade", "Fasad", 50),
    ("dach", "Dach", "Roof", "Tak", 60),
    ("fenster", "Fenster", "Windows", "Fönster", 70),
    ("terrasse", "Terrasse", "Terrace", "Terrass", 80),
    ("bad", "Bad", "Bathroom", "Badrum", 90),
    ("kueche", "Küche", "Kitchen", "Kök", 100),
    ("wasser", "Wasserinstallation", "Plumbing", "Vatteninstallation", 110),
    ("elektro", "Elektroinstallation", "Electrical installation", "Elinstallation", 120),
    ("sicherheit", "Sicherheitstechnik", "Safety equipment", "Säkerhetsutrustning", 130),
    ("garten", "Garten", "Garden", "Trädgård", 140),
]

# modus: "relativ" (ab letzter Erledigung) oder "kalender" (fester Monat)
TAETIGKEITEN = [
    {
        "schluessel": "luftfilter-wechseln",
        "de": "Luftfilter wechseln", "en": "Replace air filter", "sv": "Byta luftfilter",
        "bereiche": ["waermepumpe", "klimageraet", "lueftung"],
        "wert": 30, "einheit": "tage", "sortierung": 10,
        "hinweis_de": "Ein zugesetzter Filter kostet Wirkungsgrad und Strom. Herstellerangabe geht vor.",
        "hinweis_en": "A clogged filter costs efficiency and power. Follow the manufacturer's interval.",
        "hinweis_sv": "Ett igensatt filter kostar verkningsgrad och el. Tillverkarens intervall gäller.",
    },
    {
        "schluessel": "verdampfer-reinigen",
        "de": "Verdampfer/Lamellen reinigen", "en": "Clean evaporator fins", "sv": "Rengöra förångarens flänsar",
        "bereiche": ["waermepumpe", "klimageraet"],
        "wert": 12, "einheit": "monate", "sortierung": 20,
        "hinweis_de": "Laub und Pollen setzen die Lamellen zu; vorsichtig, sie verbiegen leicht.",
        "hinweis_en": "Leaves and pollen clog the fins; they bend easily, work gently.",
        "hinweis_sv": "Löv och pollen sätter igen flänsarna; de böjs lätt, arbeta varsamt.",
    },
    {
        "schluessel": "kondensatablauf-pruefen",
        "de": "Kondensatablauf prüfen", "en": "Check condensate drain", "sv": "Kontrollera kondensavlopp",
        "bereiche": ["waermepumpe", "klimageraet", "lueftung"],
        "wert": 6, "einheit": "monate", "sortierung": 30,
        "hinweis_de": "Ein verstopfter Ablauf führt zu Wasserschaden und im Winter zu Vereisung.",
        "hinweis_en": "A blocked drain causes water damage and, in winter, icing.",
        "hinweis_sv": "Ett igensatt avlopp ger vattenskada och isbildning på vintern.",
    },
    {
        "schluessel": "dichtheitspruefung",
        "de": "Kältemittel-Dichtheitsprüfung", "en": "Refrigerant leak check", "sv": "Läckagekontroll av köldmedium",
        "bereiche": ["waermepumpe", "klimageraet"],
        "wert": 12, "einheit": "monate", "sortierung": 40,
        "hinweis_de": "Ab bestimmter Füllmenge gesetzlich vorgeschrieben und nur vom Fachbetrieb durchführbar.",
        "hinweis_en": "Legally required above a certain charge and reserved for certified technicians.",
        "hinweis_sv": "Lagkrav över viss fyllnadsmängd och endast för certifierad tekniker.",
    },
    {
        "schluessel": "heizung-wartung",
        "de": "Heizungswartung", "en": "Heating system service", "sv": "Service av värmesystem",
        "bereiche": ["heizung", "waermepumpe"],
        "wert": 1, "einheit": "jahre", "modus": "kalender", "monat": 9, "sortierung": 50,
        "hinweis_de": "Vor der Heizperiode, nicht mittendrin -- im Oktober sind alle Betriebe ausgebucht.",
        "hinweis_en": "Before the heating season, not during it -- everyone is booked in October.",
        "hinweis_sv": "Före eldningssäsongen, inte mitt i -- i oktober är alla fullbokade.",
    },
    {
        "schluessel": "heizungsdruck-pruefen",
        "de": "Anlagendruck prüfen", "en": "Check system pressure", "sv": "Kontrollera systemtryck",
        "bereiche": ["heizung"],
        "wert": 3, "einheit": "monate", "sortierung": 60,
        "hinweis_de": "Fallender Druck ist der erste Hinweis auf ein Leck.",
        "hinweis_en": "Falling pressure is the first sign of a leak.",
        "hinweis_sv": "Sjunkande tryck är första tecknet på läckage.",
    },
    {
        "schluessel": "fassade-streichen",
        "de": "Fassade streichen", "en": "Paint facade", "sv": "Måla fasad",
        "bereiche": ["fassade"],
        "wert": 10, "einheit": "jahre", "modus": "kalender", "monat": 5, "sortierung": 70,
        "hinweis_de": "Farbton und Menge in die Notiz -- in zehn Jahren weiß das sonst niemand mehr.",
        "hinweis_en": "Record colour code and quantity in the note -- in ten years nobody remembers.",
        "hinweis_sv": "Notera kulörkod och mängd -- om tio år minns ingen.",
    },
    {
        "schluessel": "fassade-reinigen",
        "de": "Fassade reinigen", "en": "Clean facade", "sv": "Rengöra fasad",
        "bereiche": ["fassade"],
        "wert": 3, "einheit": "jahre", "modus": "kalender", "monat": 5, "sortierung": 80,
        "hinweis_de": "Algen und Grünbelag früh entfernen; das verlängert den Anstrich erheblich.",
        "hinweis_en": "Remove algae early; it markedly extends the life of the paint.",
        "hinweis_sv": "Ta bort alger tidigt; det förlänger färgens livslängd betydligt.",
    },
    {
        "schluessel": "holzverkleidung-pruefen",
        "de": "Holzverkleidung prüfen", "en": "Inspect timber cladding", "sv": "Kontrollera träpanel",
        "bereiche": ["fassade", "terrasse"],
        "wert": 12, "einheit": "monate", "sortierung": 90,
        "hinweis_de": "Besonders Sockelbereich und Wetterseite; abplatzende Farbe zieht Feuchte.",
        "hinweis_en": "Check the base and weather side; flaking paint draws in moisture.",
        "hinweis_sv": "Kontrollera sockel och vädersida; flagnande färg drar in fukt.",
    },
    {
        "schluessel": "dachrinne-reinigen",
        "de": "Dachrinne reinigen", "en": "Clean gutters", "sv": "Rensa hängrännor",
        "bereiche": ["dach"],
        "wert": 1, "einheit": "jahre", "modus": "kalender", "monat": 11, "sortierung": 100,
        "hinweis_de": "Nach dem Laubfall, vor dem ersten Frost.",
        "hinweis_en": "After leaf fall, before the first frost.",
        "hinweis_sv": "Efter lövfällningen, före första frosten.",
    },
    {
        "schluessel": "dach-sichtpruefung",
        "de": "Dach sichtprüfen", "en": "Visual roof inspection", "sv": "Okulär takbesiktning",
        "bereiche": ["dach"],
        "wert": 12, "einheit": "monate", "sortierung": 110,
        "hinweis_de": "Verrutschte Ziegel, Moos, schadhafte Anschlüsse an Kamin und Gauben.",
        "hinweis_en": "Slipped tiles, moss, damaged flashing at chimney and dormers.",
        "hinweis_sv": "Förskjutna pannor, mossa, skadade anslutningar vid skorsten och kupor.",
    },
    {
        "schluessel": "fensterbeschlaege-pflegen",
        "de": "Fensterbeschläge ölen und Dichtungen pflegen", "en": "Lubricate window fittings and seals",
        "sv": "Smörja fönsterbeslag och vårda tätningar",
        "bereiche": ["fenster"],
        "wert": 12, "einheit": "monate", "sortierung": 120,
        "hinweis_de": "Gummidichtungen mit Pflegemittel behandeln, sonst werden sie im Frost spröde.",
        "hinweis_en": "Treat rubber seals; otherwise they turn brittle in frost.",
        "hinweis_sv": "Behandla gummilister, annars blir de spröda i frost.",
    },
    {
        "schluessel": "terrasse-oelen",
        "de": "Terrassenholz ölen", "en": "Oil decking", "sv": "Olja trädäck",
        "bereiche": ["terrasse"],
        "wert": 1, "einheit": "jahre", "modus": "kalender", "monat": 5, "sortierung": 130,
        "hinweis_de": "Trockene Witterung abwarten; Produkt in die Notiz schreiben.",
        "hinweis_en": "Wait for dry weather; record the product in the note.",
        "hinweis_sv": "Vänta på torrt väder; notera produkten.",
    },
    {
        "schluessel": "toilettenspuelung-reinigen",
        "de": "Toilettenspülung reinigen", "en": "Clean toilet cistern", "sv": "Rengöra toalettens spolcistern",
        "bereiche": ["bad"],
        "wert": 12, "einheit": "monate", "sortierung": 140,
        "hinweis_de": "Kalk im Spülkasten führt zu dauerndem Nachlaufen und hohem Wasserverbrauch.",
        "hinweis_en": "Limescale in the cistern causes constant running and high water use.",
        "hinweis_sv": "Kalk i cisternen ger ständigt rinnande vatten och hög förbrukning.",
    },
    {
        "schluessel": "silikonfugen-pruefen",
        "de": "Silikonfugen prüfen", "en": "Inspect silicone joints", "sv": "Kontrollera silikonfogar",
        "bereiche": ["bad", "kueche"],
        "wert": 12, "einheit": "monate", "sortierung": 150,
        "hinweis_de": "Risse und Schimmel früh erneuern -- dahinter beginnt der Wasserschaden.",
        "hinweis_en": "Renew cracked or mouldy joints early -- water damage starts behind them.",
        "hinweis_sv": "Byt spruckna eller möglade fogar tidigt -- vattenskadan börjar bakom dem.",
    },
    {
        "schluessel": "abfluesse-reinigen",
        "de": "Abflüsse und Siphons reinigen", "en": "Clean drains and traps", "sv": "Rensa avlopp och vattenlås",
        "bereiche": ["bad", "kueche"],
        "wert": 6, "einheit": "monate", "sortierung": 160,
    },
    {
        "schluessel": "perlatoren-entkalken",
        "de": "Perlatoren entkalken", "en": "Descale tap aerators", "sv": "Avkalka strålsamlare",
        "bereiche": ["bad", "kueche", "wasser"],
        "wert": 12, "einheit": "monate", "sortierung": 170,
    },
    {
        "schluessel": "hauptabsperrhahn-bewegen",
        "de": "Hauptabsperrhahn bewegen", "en": "Exercise main shut-off valve", "sv": "Motionera huvudavstängningsventil",
        "bereiche": ["wasser"],
        "wert": 12, "einheit": "monate", "sortierung": 180,
        "hinweis_de": "Ein Ventil, das jahrelang stillsteht, lässt sich im Notfall nicht mehr schließen.",
        "hinweis_en": "A valve left untouched for years cannot be closed when it matters.",
        "hinweis_sv": "En ventil som står orörd i åratal går inte att stänga när det gäller.",
    },
    {
        "schluessel": "rauchmelder-pruefen",
        "de": "Rauchmelder prüfen", "en": "Test smoke detectors", "sv": "Testa brandvarnare",
        "bereiche": ["sicherheit"],
        "wert": 12, "einheit": "monate", "sortierung": 190,
        "hinweis_de": "Prüftaste drücken und Rauchöffnungen entstauben. Batteriewechsel getrennt führen.",
        "hinweis_en": "Press the test button and dust the smoke inlets. Track battery changes separately.",
        "hinweis_sv": "Tryck på testknappen och damma av rökintagen. För batteribyten separat.",
    },
    {
        "schluessel": "feuerloescher-pruefen",
        "de": "Feuerlöscher prüfen lassen", "en": "Have fire extinguisher serviced", "sv": "Låta serva brandsläckare",
        "bereiche": ["sicherheit"],
        "wert": 2, "einheit": "jahre", "sortierung": 200,
    },
    {
        "schluessel": "fi-schalter-pruefen",
        "de": "FI-Schutzschalter auslösen", "en": "Trip-test residual current device", "sv": "Testa jordfelsbrytare",
        "bereiche": ["elektro"],
        "wert": 6, "einheit": "monate", "sortierung": 210,
        "hinweis_de": "Prüftaste drücken; löst er nicht aus, schützt er auch im Ernstfall nicht.",
        "hinweis_en": "Press the test button; if it does not trip, it will not protect you either.",
        "hinweis_sv": "Tryck på testknappen; löser den inte ut skyddar den inte heller i skarpt läge.",
    },
    {
        "schluessel": "aussenwasser-winterfest",
        "de": "Außenwasser winterfest machen", "en": "Winterise outdoor water supply", "sv": "Vintersäkra utomhusvatten",
        "bereiche": ["wasser", "garten"],
        "wert": 1, "einheit": "jahre", "modus": "kalender", "monat": 10, "sortierung": 220,
        "hinweis_de": "Absperren und entleeren. Ein geplatztes Außenrohr merkt man erst im Frühjahr.",
        "hinweis_en": "Shut off and drain. A burst outdoor pipe only shows in spring.",
        "hinweis_sv": "Stäng av och töm. Ett sprucket utomhusrör märks först på våren.",
    },
]
